import { defineConfig } from "tsup";

export default defineConfig([
  {
    entry: {
      index: "index.ts",
      "react/index": "react/index.ts",
      "react/trpc": "react/trpc.ts",
      "react/shared": "react/shared.ts",
      "react/hooks/useMeQuery": "react/hooks/useMeQuery.ts",
      "react/hooks/useEmailVerifyCheck": "react/hooks/useEmailVerifyCheck.ts",
    },
    format: ["cjs", "esm"],
    dts: false,
    sourcemap: true,
    clean: true,
    external: [
      "react",
      "react-dom",
      "next",
      "@trpc/client",
      "@trpc/next",
      "@trpc/react-query",
      "@trpc/server",
      "@tanstack/react-query",
      "superjson",
      "zod",
    ],
    outDir: "dist",
    splitting: false,
  },
  {
    entry: {
      "server/index": "server/trpc.ts",
      "server/trpc": "server/trpc.ts",
      "server/createContext": "server/createContext.ts",
      "server/createNextApiHandler": "server/createNextApiHandler.ts",
      "server/errorFormatter": "server/errorFormatter.ts",
      "server/onErrorHandler": "server/onErrorHandler.ts",
      "server/procedures/publicProcedure": "server/procedures/publicProcedure.ts",
      "server/procedures/authedProcedure": "server/procedures/authedProcedure.ts",
      "server/routers/publicViewer/_router": "server/routers/publicViewer/_router.tsx",
    },
    format: ["cjs", "esm"],
    dts: false,
    sourcemap: true,
    external: [
      "@trpc/server",
      "@trpc/next",
      "superjson",
      "zod",
      "deasync",
      "i18next-fs-backend",
      "@calcom/trpc/server/routers/viewer/workflows/util",
    ],
    noExternal: ["@calcom/*"],
    outDir: "dist",
    target: "node18",
    bundle: true,
    splitting: false,
  },
]);
